export const IMAGE_ASSETS: Record<string, string> = {
  'title-cover': 'assets/art/ui/title-cover.png',
  'title-bg-color': 'assets/art/ui/title-bg-color.png',
  'title-bg-mono': 'assets/art/ui/title-bg-mono.png',
  'title-wordmark': 'assets/art/ui/title-wordmark.png',
  'time-vortex': 'assets/art/backgrounds/time-vortex.png',
  'bgnarator': 'assets/art/backgrounds/narrator.png',
  'bunker-underground': 'assets/art/backgrounds/bunker-underground.jpg',
  'lab-military': 'assets/art/backgrounds/lab-military.jpg',
  'lab-final': 'assets/art/backgrounds/lab-final.jpg',
  'elena-dialog': 'assets/art/characters/elena-dialog.png',
  'elena-dialog-sad': 'assets/art/characters/elena-dialog-sad.png',
  'pose-elena-hold': 'assets/art/characters/pose-elena-hold.png',
  'pose-elena-kneel': 'assets/art/characters/pose-elena-kneel.png',
  'pose-elena-resolve': 'assets/art/characters/pose-elena-resolve.png',
  'pose-arthur-muda-vial': 'assets/art/characters/pose-arthur-muda-vial.png',
  'pose-arthur-tua-reach': 'assets/art/characters/pose-arthur-tua-reach.png',
  'bg1944-far': 'assets/art/backgrounds/bg1944_far.png',
  'bg1944-mid': 'assets/art/backgrounds/bg1944_mid.png',
  'bg1944-fg': 'assets/art/backgrounds/bg1944_fg.png',
  'bg1968A-far': 'assets/art/backgrounds/bg1968A_far.png',
  'bg1968A-mid': 'assets/art/backgrounds/bg1968A_mid.png',
  'bg1968A-fg': 'assets/art/backgrounds/bg1968A_fg.png',
  'bg1968B-far': 'assets/art/backgrounds/bg1968B_far.png',
  'bg1968B-mid': 'assets/art/backgrounds/bg1968B_mid.png',
  'bg1968B-fg': 'assets/art/backgrounds/bg1968B_fg.png',
  'bg1999-far': 'assets/art/backgrounds/bg1999_far.png',
  'bg1999-mid': 'assets/art/backgrounds/bg1999_mid.png',
  'bg1999-fg': 'assets/art/backgrounds/bg1999_fg.png',
  'watch-repair-art': 'assets/art/minigames/watch-repair.png',
  'rose-bottle-broken': 'assets/art/minigames/rose-bottle-broken.png',
  'water-gem-art': 'assets/art/minigames/water-gem.jpg',
  'elena-arthur-photo': 'assets/art/minigames/elena-arthur-photo.png',
  'watch-prop': 'assets/art/props/prop_watch1944.png',
  'spotlight-prop': 'assets/art/props/prop_spotlight1944.png',
  'crate-prop': 'assets/art/props/prop_crate1944.png',
  'diary-prop': 'assets/art/props/prop_diary1968.png',
  'tape-prop': 'assets/art/props/prop_tape1968.png',
  'cryolog-prop': 'assets/art/props/prop_cryolog1999.png',
  'bonus-puzzle-board': 'assets/art/bonus/puzzle-board.jpg',
  'bonus-city-complete': 'assets/art/bonus/city-complete.jpg',
};

export const BONUS_IMAGE_ASSETS: Record<string, string> = {
  'bg2088-far': 'assets/art/backgrounds/bg2088_far.png',
  'bg2088-near': 'assets/art/backgrounds/bg2088_near.png',
  'bg2088-fg': 'assets/art/backgrounds/bg2088_fg.png',
  'bonus-diff-art': 'assets/art/bonus/spot-difference.png',
  'bonus-mawar-art': 'assets/art/bonus/rose.jpg',
  'bonus-mawar2-art': 'assets/art/bonus/rose-variant.jpg',
  'bonus-dinner-bg': 'assets/art/bonus/dinner.jpg',
  'food-spaghetti': 'assets/art/bonus/spaghetti.jpg',
  'food-nasi': 'assets/art/bonus/nasi-goreng.jpg',
  'food-udang': 'assets/art/bonus/cheese-shrimp.jpg',
  'food-steak': 'assets/art/bonus/steak.jpg',
  'bonus-cats-art': 'assets/art/bonus/cats.jpg',
  'bonus-chem-glass': 'assets/art/bonus/chemistry-glass.jpg',
  'bonus-love-glass': 'assets/art/bonus/love-glass.jpg',
};

export const PROP_SHEET_ASSETS: Record<string, string> = {
  'prop-flag1944': 'assets/art/props/prop_flag1944.png',
  'prop-lantern1944': 'assets/art/props/prop_lantern1944.png',
  'prop-flare1944': 'assets/art/props/prop_flare1944.png',
  'prop-bulb1968A': 'assets/art/props/prop_bulb1968A.png',
  'prop-radio1968A': 'assets/art/props/prop_radio1968A.png',
  'prop-beacon1968B': 'assets/art/props/prop_beacon1968B.png',
  'prop-steam1968B': 'assets/art/props/prop_steam1968B.png',
  'prop-consoleWave1999': 'assets/art/props/prop_consoleWave1999.png',
  'prop-frost1999': 'assets/art/props/prop_frost1999.png',
};

export const BONUS_PROP_SHEET_ASSETS: Record<string, string> = {
  'prop-barrel2088': 'assets/art/props/prop_barrel2088.png',
  'prop-poster2088': 'assets/art/props/prop_poster2088.png',
};

export const CHARACTER_SHEET_ASSETS: Record<string, string> = {
  'elena': 'assets/art/characters/elena_sheet.png',
  'elena-walk': 'assets/art/characters/elena-walk.png',
  'arthur-muda': 'assets/art/characters/arthur_muda_sheet.png',
  'arthur-dewasa': 'assets/art/characters/arthur_dewasa_sheet.png',
  'arthur-buron': 'assets/art/characters/arthur_buron_sheet.png',
  'arthur-tua': 'assets/art/characters/arthur_tua_sheet.png',
};

export const AUDIO_ASSETS: Record<string, string> = {
  'step-mud-0': 'assets/audio/footstep00.wav',
  'step-mud-1': 'assets/audio/footstep03.wav',
  'step-mud-2': 'assets/audio/footstep05.wav',
  'step-metal': 'assets/audio/footstep08.wav',
  'flip': 'assets/audio/bookFlip1.wav',
  'flip2': 'assets/audio/bookFlip2.wav',
  'click': 'assets/audio/metalClick.wav',
  'creak': 'assets/audio/creak2.wav',
  'rain': 'assets/audio/rain.wav',
  'wind': 'assets/audio/wind.wav',
  'fire': 'assets/audio/fire.wav',
  'hum': 'assets/audio/hum.wav',
};

export const STATIC_ASSETS = [
  ...Object.values(IMAGE_ASSETS),
  ...Object.values(BONUS_IMAGE_ASSETS),
  ...Object.values(PROP_SHEET_ASSETS),
  ...Object.values(BONUS_PROP_SHEET_ASSETS),
  ...Object.values(CHARACTER_SHEET_ASSETS),
  ...Object.values(AUDIO_ASSETS),
  'assets/video/intro.mp4',
  'assets/fonts/cinzel.ttf',
  'assets/fonts/poppins-regular.ttf',
  'assets/fonts/patrick-hand.woff2',
  'assets/fonts/patrick-hand-ext.woff2',
  'assets/fonts/OFL-Cinzel-Poppins.txt',
] as const;
