import type { WorldDefinition } from './worldTypes';

export const ERA_1944 = {
  id: '1944',
  width: 1450,
  height: 540,
  groundY: 444,
  spawn: { x: 90, y: 444 },
  defaultSurface: 'mud',
  surfaces: [
    {
      id: 'ground',
      type: 'ground',
      bounds: { x: 0, y: 444, width: 1450, height: 160 },
      material: 'mud',
    },
    {
      id: 'left-bound',
      type: 'obstacle',
      bounds: { x: -52, y: 0, width: 104, height: 444 },
      material: 'wood',
    },
    {
      id: 'right-bound',
      type: 'obstacle',
      bounds: { x: 1422, y: 0, width: 104, height: 444 },
      material: 'wood',
    },
  ],
  objects: [
    {
      id: 'watch',
      type: 'watch',
      position: { x: 420, y: 444 },
      visual: { asset: 'watch-prop', fallbackAsset: 'watch-fallback', displayHeight: 58, origin: { x: 0.5, y: 1 } },
      depth: 444,
      collider: { x: 398, y: 384, width: 44, height: 60 },
      sensor: {
        radius: 75,
        bounds: { x: 332, y: 394, width: 108, height: 100 },
      },
      action: { type: 'watchrepair' },
      prompt: { keyboard: 'SPACE — PERIKSA ARLOJI', touch: 'SPACE — ARLOJI' },
      priority: 100,
      enabled: () => true,
      completed: state => Boolean(state.watchRepaired),
      surface: 'mud',
      saveKey: 'run.watchRepaired',
      resumeX: 478,
    },
    {
      id: 'spotlight',
      type: 'challenge',
      position: { x: 700, y: 444 },
      visual: { asset: 'spotlight-prop', fallbackAsset: 'spotlight-fallback', displayHeight: 78, origin: { x: 0.5, y: 1 } },
      depth: 443,
      collider: { x: 670, y: 370, width: 60, height: 74 },
      sensor: {
        radius: 80,
        bounds: { x: 604, y: 394, width: 108, height: 100 },
      },
      action: { type: 'challenge', era: '1944' },
      prompt: { keyboard: '▼ BUKA PETA EVAKUASI', touch: '▼ BUKA PETA EVAKUASI' },
      priority: 90,
      enabled: () => true,
      completed: state => Boolean(state.challenges['1944']),
      surface: 'mud',
      saveKey: 'run.challenges.1944',
      resumeX: 765,
    },
    {
      id: 'lore_crate',
      type: 'lore',
      position: { x: 480, y: 444 },
      visual: { asset: 'crate-prop', fallbackAsset: 'lore-fallback', displayHeight: 70, origin: { x: 0.5, y: 1 } },
      depth: 442,
      sensor: {
        radius: 40,
        bounds: { x: 440, y: 394, width: 80, height: 100 },
      },
      action: { type: 'lore', id: 'lore_crate' },
      prompt: { keyboard: '▼ periksa', touch: 'SPACE — PERIKSA' },
      priority: 20,
      enabled: () => true,
      completed: state => Boolean(state.inspected.lore_crate),
      surface: 'mud',
      saveKey: 'save.inspected.lore_crate',
    },
    {
      id: 'lore_flare',
      type: 'lore',
      position: { x: 1000, y: 444 },
      visual: {
        asset: 'prop-flare1944',
        fallbackAsset: 'lore-fallback',
        frame: 0,
        displayHeight: 104,
        origin: { x: 0.5, y: 1 },
      },
      depth: 442,
      sensor: {
        radius: 40,
        bounds: { x: 960, y: 394, width: 80, height: 100 },
      },
      action: { type: 'lore', id: 'lore_flare' },
      prompt: { keyboard: '▼ periksa', touch: 'SPACE — PERIKSA' },
      priority: 20,
      enabled: () => true,
      completed: state => Boolean(state.inspected.lore_flare),
      surface: 'mud',
      saveKey: 'save.inspected.lore_flare',
    },
    {
      id: 'arthur',
      type: 'exit',
      position: { x: 1240, y: 444 },
      visual: {
        asset: 'arthur-muda',
        fallbackAsset: 'arthur-fallback',
        frame: 0,
        displayHeight: 112,
        origin: { x: 0.5, y: 1 },
        flipX: true,
      },
      depth: 444,
      sensor: {
        radius: 186.5,
        bounds: { x: 1077, y: 394, width: 373, height: 100 },
      },
      action: { type: 'dialog', node: 'n_b1' },
      priority: 10,
      auto: true,
      enabled: state => Boolean(state.watchRepaired) && Boolean(state.challenges['1944']),
      completed: () => false,
      surface: 'mud',
      saveKey: 'save.seen.n_b1',
    },
  ],
} satisfies WorldDefinition;
