import type { WorldDefinition } from './worldTypes';

export const ERA_1999 = {
  id: '1999',
  width: 1100,
  height: 540,
  groundY: 444,
  spawn: { x: 90, y: 444 },
  defaultSurface: 'metal',
  surfaces: [
    {
      id: 'ground',
      type: 'ground',
      bounds: { x: 0, y: 444, width: 1100, height: 160 },
      material: 'metal',
    },
    {
      id: 'left-bound',
      type: 'obstacle',
      bounds: { x: -52, y: 0, width: 104, height: 444 },
      material: 'metal',
    },
    {
      id: 'right-bound',
      type: 'obstacle',
      bounds: { x: 1072, y: 0, width: 104, height: 444 },
      material: 'metal',
    },
  ],
  objects: [
    {
      id: 'gem',
      type: 'puzzle',
      position: { x: 250, y: 444 },
      visual: { asset: 'water-gem-art', displayHeight: 64, origin: { x: 0.5, y: 1 } },
      depth: 444,
      collider: { x: 225, y: 384, width: 50, height: 60 },
      sensor: {
        radius: 75,
        bounds: { x: 185, y: 394, width: 110, height: 100 },
      },
      action: { type: 'puzzle', id: 'gem' },
      prompt: { keyboard: 'SPACE — PUTAR PERMATA AIR', touch: 'SPACE — PERMATA AIR' },
      priority: 100,
      enabled: () => true,
      completed: state => Boolean(state.gemAligned),
      surface: 'metal',
      saveKey: 'run.gemAligned',
      resumeX: 308,
    },
    {
      id: 'photo',
      type: 'puzzle',
      position: { x: 455, y: 444 },
      visual: { asset: 'elena-arthur-photo', displayHeight: 64, origin: { x: 0.5, y: 1 } },
      depth: 443,
      collider: { x: 430, y: 384, width: 50, height: 60 },
      sensor: {
        radius: 75,
        bounds: { x: 390, y: 394, width: 110, height: 100 },
      },
      action: { type: 'puzzle', id: 'photo' },
      prompt: { keyboard: 'SPACE — REKATKAN FOTO', touch: 'SPACE — REKATKAN FOTO' },
      priority: 90,
      enabled: () => true,
      completed: state => Boolean(state.photoRepaired),
      surface: 'metal',
      saveKey: 'run.photoRepaired',
      resumeX: 513,
    },
    {
      id: 'cryo',
      type: 'challenge',
      position: { x: 590, y: 444 },
      visual: { asset: 'prop-consoleWave1999', displayHeight: 74, origin: { x: 0.5, y: 1 } },
      depth: 442,
      collider: { x: 560, y: 370, width: 60, height: 74 },
      sensor: {
        radius: 80,
        bounds: { x: 520, y: 394, width: 120, height: 100 },
      },
      action: { type: 'challenge', era: '1999' },
      prompt: { keyboard: '▼ STABILISASI KRIO', touch: '▼ STABILISASI KRIO' },
      priority: 80,
      enabled: () => true,
      completed: state => Boolean(state.challenges['1999']),
      surface: 'metal',
      saveKey: 'run.challenges.1999',
      resumeX: 655,
    },
    {
      id: 'lore_clip',
      type: 'lore',
      position: { x: 420, y: 444 },
      visual: { asset: 'cryolog-prop', fallbackAsset: 'lore-fallback', displayHeight: 54, origin: { x: 0.5, y: 1 } },
      depth: 441,
      sensor: {
        radius: 48,
        bounds: { x: 390, y: 394, width: 60, height: 100 },
      },
      action: { type: 'lore', id: 'lore_clip' },
      prompt: { keyboard: 'SPACE — BACA LOG KAPSUL', touch: '▼ BACA LOG KAPSUL' },
      priority: 60,
      enabled: () => true,
      completed: state => Boolean(state.inspected.lore_clip),
      surface: 'metal',
      saveKey: 'save.inspected.lore_clip',
    },
    {
      id: 'arthur',
      type: 'exit',
      position: { x: 900, y: 444 },
      visual: {
        asset: 'arthur-tua',
        fallbackAsset: 'arthur-fallback',
        frame: 0,
        displayHeight: 112,
        origin: { x: 0.5, y: 1 },
        flipX: true,
      },
      depth: 444,
      sensor: {
        radius: 160,
        bounds: { x: 760, y: 394, width: 320, height: 100 },
      },
      action: { type: 'dialog', node: 'n_b3' },
      priority: 10,
      auto: true,
      enabled: state => Boolean(state.gemAligned) && Boolean(state.photoRepaired) && Boolean(state.challenges['1999']),
      completed: () => false,
      surface: 'metal',
      saveKey: 'save.seen.n_b3',
    },
  ],
} satisfies WorldDefinition;
